introduced helper: printing functions, message format now mimics makepkg; adjusted code formatting;

diff --git a/ffcast b/ffcast
--- a/ffcast
+++ b/ffcast
@@ -34,10 +34,54 @@ XRECTSEL=
 BORDERLESS='1'
 CASTSPAN=
 FFMOD='2'
+COLORMSG='1'
 DEBUG='/dev/null'
 # }}}
 
 # {{{ functions
+# {{{ helper: printing
+msg () {
+    local mesg=$1; shift
+    if [ $COLORMSG ]; then
+        printf "\033[1;32m==> \033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
+    else
+        printf "==> ${mesg}\n" "$@" >&2
+    fi
+}
+msg2 () {
+    local mesg=$1; shift
+    if [ $COLORMSG ]; then
+        printf "\033[1;34m  -> \033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
+    else
+        printf "==> ${mesg}\n" "$@" >&2
+    fi
+}
+wrn () {
+    local mesg=$1; shift
+    if [ $COLORMSG ]; then
+        printf "\033[1;33m(WW) \033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
+    else
+        printf "(WW) ${mesg}\n" "$@" >&2
+    fi
+}
+err () {
+    local mesg=$1; shift
+    if [ $COLORMSG ]; then
+        printf "\033[1;31m(EE) \033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >&2
+    else
+        printf "(EE) ${mesg}\n" "$@" >&2
+    fi
+}
+dbg () {
+    local mesg=$1; shift
+    if [ $COLORMSG ]; then
+        printf "\033[1;37m(DD) \033[1;0m\033[1;1m ${mesg}\033[1;0m\n" "$@" >"${DEBUG}"
+    else
+        printf "(DD) ${mesg}\n" "$@" >&2
+    fi
+}
+# }}}
+# {{{ usage
 usage () {
 local ffcast=$(basename "${PRGSELF}")
 cat << EOF
@@ -69,138 +113,20 @@ cat << EOF
     -r,--rate:       Frame Rate (FPS) (def: ${FPS})
     -t,--duration:   Restrict cast video duration in seconds; alternatively hh:mm:ss[.xxx]
 
-    -v,--debug       print verbose debug info to stderr
+    -v,--debug       Print verbose debug info to stderr
+       --nocolor     Disable colors in messages
     -h,--help        Show this message
 
 EOF
 }
+# }}}
+# {{{ helper: maths
 # tucker M N expands N to mod M
 # nipper M N shrinks N to mod M
 tucker () { local m=$1; shift; echo $(( $1 + ($m - ($1 % $m)) % $m )); }
 nipper () { local m=$1; shift; echo $(( $1 / $m * $m )); }
 min () { LC_ALL=C ; echo "$@" | tr ' ' '\n' | grep . | sort -g | head -1; }
 max () { LC_ALL=C ; echo "$@" | tr ' ' '\n' | grep . | sort -g | tail -1; }
-check_apps () {
-    local app oops=
-    for app in ffmpeg xwininfo xrectsel bc; do
-        which "${app}" &>/dev/null || {
-        echo "(EE) ${app} not found in PATH"; oops=1; }
-    done
-    [ "${oops}" ] && {
-    echo "(EE) Required program(s) not found in PATH"; exit 1; }
-}
-rootwin_xy () {
-    # global: defines: RLEN_X RLEN_Y
-    local regex='Width: +([0-9]+).*Height: +([0-9]+)'
-    local wininfo=$(LANG='' xwininfo -root)
-    if [[ "$wininfo" =~ $regex ]]
-    then
-        RLEN_X=${BASH_REMATCH[1]}
-        RLEN_Y=${BASH_REMATCH[2]}
-    else
-        echo "(EE) xwininfo returned wrong Data (root):"
-        echo "$wininfo" ; exit 1
-    fi
-    echo "(DD) geometry: root: $RLEN_X x $RLEN_Y" >"${DEBUG}"
-}
-geo_sanity () {
-    # global: LEN_X LEN_Y POS_X POS_Y RLEN_X RLEN_Y FFMOD DEBUG
-    # mod FFMOD & inside screen
-    LEN_X=$(tucker ${FFMOD} $LEN_X)
-    LEN_Y=$(tucker ${FFMOD} $LEN_Y)
-    echo "(DD) geometry: mod ${FFMOD}: $LEN_X x $LEN_Y" >"${DEBUG}"
-    LEN_X=$(min $LEN_X $(nipper ${FFMOD} $(( RLEN_X - POS_X ))))
-    LEN_Y=$(min $LEN_Y $(nipper ${FFMOD} $(( RLEN_Y - POS_Y ))))
-    echo "(DD) geometry: in screen: $LEN_X x $LEN_Y" >"${DEBUG}"
-    echo ":: Capture geometry: ${LEN_X}x${LEN_Y}+${POS_X}+${POS_Y}"
-}
-window_info () {
-    local wininfo regex SOP_X SOP_Y DEC_W=0
-    case "${WINID,,}" in
-        '')
-        echo ":: Click to select ${WINNO:-1} window(s) to be captured"
-        for ((i=1;i<=${WINNO:-1};i++)); do
-            WINIDS+=("$i")
-        done
-        wininfo () { LANG='' xwininfo ; } ;;
-        root)
-        echo ":: Fullscreen capture may take a while"
-        WINIDS=($WINID)
-        wininfo () { LANG='' xwininfo -root ; } ;;
-        *)
-        echo ":: Selected window(s): $WINID"
-        WINIDS=($WINID)
-        wininfo () { LANG='' xwininfo -id $WINID ; } ;;
-    esac
-    regex='Border width: +([0-9]+).*Corners: +\+(-?[0-9]+)\+(-?[0-9]+).* +-(-?[0-9]+)-(-?[0-9]+)'
-    # support for multiple windows
-    for WINID in "${WINIDS[@]}"; do
-        echo -ne "\033[s:: Selecting $WINID of ${#WINIDS[@]} window(s)"
-        wininfo=$(wininfo) || { echo "(WW) xwininfo error @ window $WINID"; continue; }
-        if [[ "$wininfo" =~ $regex ]]
-        then
-            [ "$BORDERLESS" ] && DEC_W=${BASH_REMATCH[1]}
-            # inside screen, they must be -ge 0 [max]
-            # multiple windows, we pick the [min]
-            POS_X=$(min ${POS_X} $(max 0 $(( ${BASH_REMATCH[2]} + DEC_W ))))
-            POS_Y=$(min ${POS_Y} $(max 0 $(( ${BASH_REMATCH[3]} + DEC_W ))))
-            SOP_X=$(min ${SOP_X} $(max 0 $(( ${BASH_REMATCH[4]} + DEC_W ))))
-            SOP_Y=$(min ${SOP_Y} $(max 0 $(( ${BASH_REMATCH[5]} + DEC_W ))))
-        else
-            echo "(EE) xwininfo returned wrong Data:"
-            echo "$wininfo" ; exit 1
-        fi
-        echo -ne '\033[u\033[K'
-        echo "(DD) geometry: ($POS_X,$POS_Y) ($SOP_X,$SOP_Y)" >"${DEBUG}"
-    done
-    [ -z "$wininfo" ] && { echo "(EE) xwininfo failure"; exit 1; }
-    unset wininfo
-    LEN_X=$(( RLEN_X - POS_X - SOP_X ))
-    LEN_Y=$(( RLEN_Y - POS_Y - SOP_Y ))
-    geo_sanity
-}
-rectang_sel () {
-    local regex='([0-9]+)x([0-9]+)\+([0-9]+)\+([0-9]+)'
-    echo ":: Select area to be captured by dragging the mouse"
-    local rsgeo=$(xrectsel)
-    if [[ "${rsgeo}" =~ $regex ]]
-    then
-        LEN_X=${BASH_REMATCH[1]}
-        LEN_Y=${BASH_REMATCH[2]}
-        POS_X=${BASH_REMATCH[3]}
-        POS_Y=${BASH_REMATCH[4]}
-    else
-        echo "(EE) xrectsel returned wrong Data:"
-        echo "$rsgeo" ; exit 1
-    fi
-    geo_sanity
-}
-listEVcodecs () {
-    echo x264
-    ffmpeg -formats 2>/dev/null | \
-    sed '/^ \+[D ]EV[S ][D ][T ] \+\([^ ]*\).*/!d;s//\1/'
-}
-valueEVcodec () {
-    local evc="$1" EVC=
-    [[ "${evc,,}" =~ ^\?$|^list$ ]] && { listEVcodecs; exit 0; }
-    EVC=$(listEVcodecs | grep -Fxi "$evc" 2>"${DEBUG}") && CODEC="$EVC" \
-    || {
-    echo "(WW) ffmpeg: unsupported codec: $evc"
-    echo "(WW) falling back to codec: ${CODEC}"; }
-}
-listEVformats () {
-    ffmpeg -formats 2>/dev/null | \
-    sed '/^ \+[D ]E \+\([^ ]*\).*/!d;s//\1/'
-}
-valueEVformat () {
-    GUESSFMT=
-    local evf="$1" EVF=
-    [[ "${evf,,}" =~ ^\?$|^list$ ]] && { listEVformats; exit 0; }
-    EVF=$(listEVformats | grep -Fxi "$evf" 2>"${DEBUG}") && FORMAT="$EVF" \
-    || {
-    echo "(WW) ffmpeg: unsupported format: $evf"
-    echo "(WW) falling back to format: ${FORMAT}"; }
-}
 hhmmss2sec () {
     # ffmpeg -t option does support hh:mm:ss[.xxx], but not mm:ss -- too dumb
     # so let's convert hh:mm:ss to seconds so ffmpeg can understand
@@ -220,6 +146,140 @@ sec2hhmmss () {
     ss=$(printf "%05.2f" $(bc <<< "${sec} % 60"))
     echo "${hh}:${mm}:${ss}"
 }
+# }}}
+# {{{ core functions
+# {{{ helper: core
+check_apps () {
+    local app oops=
+    for app in ffmpeg xwininfo xrectsel bc; do
+        which "${app}" &>/dev/null || {
+        err "${app} not found in PATH"; oops=1; }
+    done
+    [ "${oops}" ] && {
+    err "Required program(s) not found in PATH"; exit 1; }
+}
+rootwin_xy () {
+    # global: defines: RLEN_X RLEN_Y
+    local regex='Width: +([0-9]+).*Height: +([0-9]+)'
+    local wininfo=$(LANG='' xwininfo -root 2>"${DEBUG}")
+    if [[ "$wininfo" =~ $regex ]]
+    then
+        RLEN_X=${BASH_REMATCH[1]}
+        RLEN_Y=${BASH_REMATCH[2]}
+    else
+        err "xwininfo returned wrong Data (root):"
+        echo "$wininfo" ; exit 1
+    fi
+    dbg "geometry: root: $RLEN_X x $RLEN_Y"
+}
+geo_sanity () {
+    # global: LEN_X LEN_Y POS_X POS_Y RLEN_X RLEN_Y FFMOD DEBUG
+    # mod FFMOD & inside screen
+    LEN_X=$(tucker ${FFMOD} $LEN_X)
+    LEN_Y=$(tucker ${FFMOD} $LEN_Y)
+    dbg "geometry: mod ${FFMOD}: $LEN_X x $LEN_Y"
+    LEN_X=$(min $LEN_X $(nipper ${FFMOD} $(( RLEN_X - POS_X ))))
+    LEN_Y=$(min $LEN_Y $(nipper ${FFMOD} $(( RLEN_Y - POS_Y ))))
+    dbg "geometry: in screen: $LEN_X x $LEN_Y"
+    msg "Capture geometry: ${LEN_X}x${LEN_Y}+${POS_X}+${POS_Y}"
+}
+# }}}
+# {{{ define capture area with xwininfo
+window_info () {
+    local wininfo regex SOP_X SOP_Y DEC_W=0
+    case "${WINID,,}" in
+        '')
+        msg "Click to select ${WINNO:-1} window(s) to be captured"
+        for ((i=1;i<=${WINNO:-1};i++)); do
+            WINIDS+=("$i")
+        done
+        wininfo () { LANG='' xwininfo ; } ;;
+        root)
+        msg "Fullscreen capture may take a while"
+        WINIDS=($WINID)
+        wininfo () { LANG='' xwininfo -root ; } ;;
+        *)
+        msg "Selected window(s): $WINID"
+        WINIDS=($WINID)
+        wininfo () { LANG='' xwininfo -id $WINID ; } ;;
+    esac
+    regex='Border width: +([0-9]+).*Corners: +\+(-?[0-9]+)\+(-?[0-9]+).* +-(-?[0-9]+)-(-?[0-9]+)'
+    # support for multiple windows
+    for WINID in "${WINIDS[@]}"; do
+        #echo -ne '\033[s'
+        msg2 "Selecting $WINID of ${#WINIDS[@]} window(s)"
+        wininfo=$(wininfo 2>"${DEBUG}") || { wrn "xwininfo error @ window $WINID"; continue; }
+        if [[ "$wininfo" =~ $regex ]]
+        then
+            [ "$BORDERLESS" ] && DEC_W=${BASH_REMATCH[1]}
+            # inside screen, they must be -ge 0 [max]
+            # multiple windows, we pick the [min]
+            POS_X=$(min ${POS_X} $(max 0 $(( ${BASH_REMATCH[2]} + DEC_W ))))
+            POS_Y=$(min ${POS_Y} $(max 0 $(( ${BASH_REMATCH[3]} + DEC_W ))))
+            SOP_X=$(min ${SOP_X} $(max 0 $(( ${BASH_REMATCH[4]} + DEC_W ))))
+            SOP_Y=$(min ${SOP_Y} $(max 0 $(( ${BASH_REMATCH[5]} + DEC_W ))))
+        else
+            err "xwininfo returned wrong Data:"
+            echo "$wininfo" ; exit 1
+        fi
+        #echo -ne '\033[u\033[K'
+        #echo -ne '\033[A\033[K'
+        dbg "geometry: ($POS_X,$POS_Y) ($SOP_X,$SOP_Y)"
+    done
+    [ -z "$wininfo" ] && { err "xwininfo failure"; exit 1; }
+    unset wininfo
+    LEN_X=$(( RLEN_X - POS_X - SOP_X ))
+    LEN_Y=$(( RLEN_Y - POS_Y - SOP_Y ))
+    geo_sanity
+}
+# }}}
+# {{{ define capture area with xrectsel
+rectang_sel () {
+    local regex='([0-9]+)x([0-9]+)\+([0-9]+)\+([0-9]+)'
+    msg "Select area to be captured by dragging the mouse"
+    local rsgeo=$(xrectsel)
+    if [[ "${rsgeo}" =~ $regex ]]
+    then
+        LEN_X=${BASH_REMATCH[1]}
+        LEN_Y=${BASH_REMATCH[2]}
+        POS_X=${BASH_REMATCH[3]}
+        POS_Y=${BASH_REMATCH[4]}
+    else
+        err "xrectsel returned wrong Data:"
+        echo "$rsgeo" ; exit 1
+    fi
+    geo_sanity
+}
+# }}}
+# {{{ codecs checker
+listEVcodecs () {
+    echo x264
+    ffmpeg -formats 2>/dev/null | \
+    sed '/^ \+[D ]EV[S ][D ][T ] \+\([^ ]*\).*/!d;s//\1/'
+}
+valueEVcodec () {
+    local evc="$1" EVC=
+    [[ "${evc,,}" =~ ^\?$|^list$ ]] && { listEVcodecs; exit 0; }
+    EVC=$(listEVcodecs | grep -Fxi "$evc" 2>"${DEBUG}") && CODEC="$EVC" \
+    || {
+    wrn "ffmpeg: unsupported codec: $evc"
+    wrn "falling back to codec: ${CODEC}"; }
+}
+listEVformats () {
+    ffmpeg -formats 2>/dev/null | \
+    sed '/^ \+[D ]E \+\([^ ]*\).*/!d;s//\1/'
+}
+valueEVformat () {
+    GUESSFMT=
+    local evf="$1" EVF=
+    [[ "${evf,,}" =~ ^\?$|^list$ ]] && { listEVformats; exit 0; }
+    EVF=$(listEVformats | grep -Fxi "$evf" 2>"${DEBUG}") && FORMAT="$EVF" \
+    || {
+    wrn "ffmpeg: unsupported format: $evf"
+    wrn "falling back to format: ${FORMAT}"; }
+}
+# }}}
+# }}}
 # }}}
 
 # {{{ options
@@ -243,7 +303,8 @@ until [ -z "$1" ] ; do
         -p|--preset)     PRESET="$2" ; shift 2 ;;
         -o|--output)     OUTPUT="$2" ; shift 2 ;;
         -v|--debug)      DEBUG='/dev/stderr' ; shift ;;
-        *)               echo "(EE) invalid option $1" ; exit 1 ;;
+           --nocolor)    COLORMSG= ; shift ;;
+        *)               err "invalid option $1" ; exit 1 ;;
     esac
 done
 # }}}
@@ -251,21 +312,21 @@ done
 # {{{ main
 check_apps
 
-[ -z "${DISPLAY}" ] && { echo '(EE) X not running'; exit 1; }
+[ -z "${DISPLAY}" ] && { err "X not running"; exit 1; }
 
 # is there a way to do ${OUTPUT##*.,,} ?
 #( ext="${OUTPUT##*.}"; [[ "${ext,,}" =~ ^avi$|^mkv$|^mp4$ ]] ) || {
-#echo "(WW) output: unsupported format"
-#echo "(WW) output: falling back to ${EXT}"
+#wrn "output: unsupported format"
+#wrn "output: falling back to ${EXT}"
 #OUTPUT="${OUTPUT}.${EXT}"; }
 # this block of code should be gone forever!!
 # -- well, only when we can deal with format AND codec well enough?
 # or develop this further to a function check_extention()?
 
 while [ -f "${OUTPUT}" ] ; do
-    echo "(WW) output: file exists: ${OUTPUT}"
+    wrn "output: file exists: ${OUTPUT}"
     OUTPUT="${OUTPUT%.*}.${PRGNAME:-0}.${OUTPUT##*.}"
-    echo "(WW) output: output name: ${OUTPUT}"
+    wrn "output: output name: ${OUTPUT}"
 done
 
 case "${CODEC,,}" in
@@ -277,25 +338,25 @@ esac
 VCODEC="-vcodec ${VCODEC}"
 [ "${GUESSFMT}" ] && FORMAT= || FORMAT="-f ${FORMAT}"
 # maybe add check_extention when GUESSFMT=1?
-echo "(DD) VCODEC: ${VCODEC}" >"${DEBUG}"
-echo "(DD) FORMAT: ${FORMAT}" >"${DEBUG}"
+dbg "VCODEC: ${VCODEC}"
+dbg "FORMAT: ${FORMAT}"
 
 rootwin_xy
 [ "${XRECTSEL}" ] && rectang_sel || window_info
 
 [ "${CASTSPAN}" ] && {
 CASTSPAN=$(hhmmss2sec ${CASTSPAN})
-echo ":: Capture duration limited to [$(sec2hhmmss ${CASTSPAN})]"
+msg "Capture duration limited to [$(sec2hhmmss ${CASTSPAN})]"
 CASTSPAN="-t ${CASTSPAN}"; }
 
-echo ":: Capture started, press [q] to finish"
+msg "Capture started, press [q] to finish"
 # -threads 0 was in the original, but segfaults with, say -vcodec flv
 ffmpeg -r ${FPS} -v 1  \
     -s ${LEN_X}x${LEN_Y} -an \
     -f x11grab -i ${DISPLAY}+${POS_X},${POS_Y} \
     ${VCODEC} ${FORMAT} ${CASTSPAN} \
     "${OUTPUT}" 2>"${DEBUG}" || \
-echo "(EE) ffmpeg: failed, try running with --debug"
-echo ":: output: output name: ${OUTPUT}"
+err "ffmpeg: failed, try running with --debug"
+msg "Output filename: ${OUTPUT}"
 # }}}
 # vim: fdm=marker
